packages:
  - packages/*

catalogs:
  build:
    comptime.ts: ^0.8.0
    rolldown: ^1.0.0-beta.54
    vite: ^8.0.0-beta.2
  db:
    better-sqlite3: ^12.5.0
    reflect-metadata: ^0.2.2
    sqlite3: ^5.1.7
    typeorm: ^0.3.28
  discord:
    bufferutil: ^4.1.0
    discord.js: 14.25.1
  linting:
    '@stylistic/eslint-plugin': ^5.6.1
    eslint: ^9.39.2
    eslint-plugin-oxlint: ^1.34.0
    jiti: ^2.6.1
    oxlint: ^1.34.0
    typescript-eslint: ^8.50.0
  types:
    '@types/better-sqlite3': ^7.6.13
    '@types/bun': ^1.3.5
    '@types/node': ^25.0.3
    zod: ^4.2.1
  utils:
    '@sapphire/result': ^2.8.0
    chalk: ^5.6.2
    commander: ^14.0.2
    comptime.ts: ^0.8.0
    cronbake: ^0.4.0

minimumReleaseAge: 7280

onlyBuiltDependencies:
  - better-sqlite3
  - bufferutil
  - esbuild
  - sqlite3

shamefullyHoist: true
