minimumReleaseAge: 7280
packages:
  - "packages/*"

catalogs:
  discord:
    discord.js: ^14.25.1
    bufferutil: ^4.1.0
  db:
    better-sqlite3: ^12.5.0
    typeorm: ^0.3.28
    reflect-metadata: ^0.2.2
  utils:
    chalk: ^5.6.2
    commander: ^14.0.2
    cronbake: ^0.4.0
    rust-optionals: ^3.0.0
    comptime.ts: ^0.8.0
  linting:
    "@stylistic/eslint-plugin": ^5.6.1
    eslint: ^9.39.2
    eslint-plugin-oxlint: ^1.34.0
    jiti: ^2.6.1
    oxlint: ^1.34.0
    typescript-eslint: ^8.50.0
  types:
    "@types/bun": ^1.3.5
    "@types/node": ^25.0.3
