packages:
  - packages/*

catalogs:
  build:
    comptime.ts: ^0.8.0
    rolldown: 1.0.0-beta.59
    vite: ^8.0.0-beta.2
  db:
    better-sqlite3: ^12.5.0
    reflect-metadata: ^0.2.2
    sqlite3: ^5.1.7
    typeorm: ^0.3.28
  discord:
    bufferutil: ^4.1.0
    discord.js: 14.25.1
  linting:
    dprint: ^0.51.1
    oxlint: ^1.38.0
    oxlint-tsgolint: ^0.10.1
  types:
    '@types/better-sqlite3': ^7.6.13
    '@types/bun': ^1.3.5
    '@types/node': ^25.0.3
    '@typescript/native-preview': 7.0.0-dev.20260108.1
    zod: ^4.3.0
  utils:
    '@sapphire/result': ^2.8.0
    chalk: ^5.6.2
    commander: ^14.0.2
    comptime.ts: ^0.8.0
    cronbake: ^0.4.0

minimumReleaseAge: 720

onlyBuiltDependencies:
  - better-sqlite3
  - bufferutil
  - esbuild
  - sqlite3
  - dprint
